name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install LaTeX
      run: |
        sudo apt install texlive-latex-base
    - name: Make Doc
      run: |
        make
    - name: Upload PDFs
      uses: actions/upload-artifact@v2
      with:
        name: linux-packaging
        path: linux-packaging.pdf
